x-veld:
  executable:
    about:
      description: >
        "Converts NER json data to spaCy docbin, and prepares it for training by splitting it into 
        train, dev, eval subsets, and shuffling them randomly."
      topic:
        - "ETL"
        - "NLP"
        - "Machine learning"
    input:
      -
        type: "file"
        format: "json"
        content: "Named entity recognition gold data"
        path: /veld/input/data.json
      -
        type: "environment variable"
        name: "train" 
        optional: true
        default: 80
      -
        type: "environment variable"
        name: "dev" 
        optional: true
        default: 10
      -
        type: "environment variable"
        name: "eval" 
        optional: true
        default: 10
      -
        type: "environment variable"
        name: "seed" 
        optional: true
        default: 42
    output:
      -
        type: "folder"
        format: "spaCy DocBin"
        content: "Named entity recognition gold data"
        path: /veld/output/a/
      -
        type: "file"
        format: "txt"
        content: "log"
        path: /veld/output/convert.log

services:
  veld:
    build: .
    volumes:
      - ./convert.py:/veld/executable/convert.py
    environment:
      train: 80
      dev: 10
      eval: 10
      seed: 42
    command: bash -c "python /veld/executable/convert.py |& tee /veld/output/convert.log"

